version: '3'
services:
  # Spring Boot application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090" # Map the host port to the container port
    depends_on:
      - db # Depends on the database service

  # MySQL database
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: test
    ports:
      - "3306:3306" # Map the host port to the container port


